"""remove provider

Revision ID: bc37715adfe0
Revises: f74325875154
Create Date: 2024-01-12 04:38:46.419422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc37715adfe0'
down_revision = 'f74325875154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    op.drop_column('products', 'reject_reason')
    op.drop_column('products', 'published_date')
    op.drop_column('products', 'created_by')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('provider', mysql.ENUM('app', 'google.com', 'apple.com'), nullable=False))
    op.add_column('products', sa.Column('created_by', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('published_date', mysql.DATETIME(), nullable=True))
    op.add_column('products', sa.Column('reject_reason', mysql.TEXT(), nullable=True))
    op.add_column('products', sa.Column('status', mysql.ENUM('waiting', 'unpublished', 'published', 'rejected'), nullable=True))
    # ### end Alembic commands ###
